# Tensor Basics

* Converting NumPy arrays to PyTorch tensors
* Creating tensors from scratch


In [54]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.4.0'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
print(arr.dtype)

int64


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
x = torch.from_numpy(arr)

In [10]:
x

tensor([1, 2, 3, 4, 5])

In [11]:
print(x)

tensor([1, 2, 3, 4, 5])


In [12]:
print(x.dtype)

torch.int64


In [13]:
print(type(x))

<class 'torch.Tensor'>


In [14]:
print(x.type())

torch.LongTensor


In [15]:
arr2 = np.arange(0.,12.).reshape(4,3)

In [16]:
print(arr2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [17]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


<h2><a href='https://pytorch.org/docs/stable/tensors.html'>Tensor Datatypes</a></h2>
<table style="display: inline-block">
<tr><th>TYPE</th><th>NAME</th><th>EQUIVALENT</th><th>TENSOR TYPE</th></tr>
<tr><td>32-bit integer (signed)</td><td>torch.int32</td><td>torch.int</td><td>IntTensor</td></tr>
<tr><td>64-bit integer (signed)</td><td>torch.int64</td><td>torch.long</td><td>LongTensor</td></tr>
<tr><td>16-bit integer (signed)</td><td>torch.int16</td><td>torch.short</td><td>ShortTensor</td></tr>
<tr><td>32-bit floating point</td><td>torch.float32</td><td>torch.float</td><td>FloatTensor</td></tr>
<tr><td>64-bit floating point</td><td>torch.float64</td><td>torch.double</td><td>DoubleTensor</td></tr>
<tr><td>16-bit floating point</td><td>torch.float16</td><td>torch.half</td><td>HalfTensor</td></tr>
<tr><td>8-bit integer (signed)</td><td>torch.int8</td><td></td><td>CharTensor</td></tr>
<tr><td>8-bit integer (unsigned)</td><td>torch.uint8</td><td></td><td>ByteTensor</td></tr></table>

In [18]:
# Using torch.from_numpy()
arr = np.arange(0,5)
t = torch.from_numpy(arr)
print(t)

tensor([0, 1, 2, 3, 4])


However, the torch.tensor() function always makes a copy.

In [19]:
arr[2]=77
print(t)

tensor([ 0,  1, 77,  3,  4])


In [20]:
# Using torch.tensor()
arr = np.arange(0,5)
t = torch.tensor(arr)
print(t)

tensor([0, 1, 2, 3, 4])


In [22]:
arr[2]=77
print(t)

tensor([0, 1, 2, 3, 4])


In [23]:
data = np.array([1,2,3])

In [24]:
a = torch.Tensor(data)  # Equivalent to cc = torch.FloatTensor(data)
print(a, a.type())

tensor([1., 2., 3.]) torch.FloatTensor


In [25]:
b = torch.tensor(data)
print(b, b.type())

tensor([1, 2, 3]) torch.LongTensor


In [26]:
c = torch.tensor(data, dtype=torch.long)
print(c, c.type())

tensor([1, 2, 3]) torch.LongTensor


### Creating tensors from scratch

In [29]:
x = torch.empty(4,3)

In [30]:
x

tensor([[4.9246e-37, 0.0000e+00, 4.8732e-37],
        [0.0000e+00, 8.9683e-44, 0.0000e+00],
        [1.1210e-43, 0.0000e+00, 4.8732e-37],
        [0.0000e+00, 4.2659e-08, 2.9575e-18]])

In [31]:
x = torch.zeros(4, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [32]:
x = torch.arange(0,18,2).reshape(3,3)
print(x)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])


In [33]:
x = torch.linspace(0,18,12).reshape(3,4)
print(x)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])


In [34]:
x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.dtype)
print(x.type())

tensor([1, 2, 3, 4])
torch.int64
torch.LongTensor


In [35]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)
print(x.type())

tensor([5., 6., 7.])
torch.float32
torch.FloatTensor


In [36]:
x = torch.tensor([8,9,-3], dtype=torch.int)
print(x)
print(x.dtype)
print(x.type())

tensor([ 8,  9, -3], dtype=torch.int32)
torch.int32
torch.IntTensor


In [37]:
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


In [40]:
x = torch.rand(4, 3)
print(x)

tensor([[0.1286, 0.4814, 0.9185],
        [0.8256, 0.2005, 0.7322],
        [0.9354, 0.8311, 0.0108],
        [0.6747, 0.6150, 0.0061]])


In [41]:
x = torch.randn(4, 3)
print(x)

tensor([[-0.0051,  0.4457,  1.0709],
        [-0.5092, -0.2157,  0.6207],
        [ 0.6886, -0.9626,  1.5509],
        [-1.2836,  2.0959, -1.6183]])


In [43]:
x = torch.randint(0, 15, (4, 3))
print(x)

tensor([[ 5,  1,  3],
        [ 6,  3,  3],
        [ 5,  1, 10],
        [ 9,  0, 13]])


In [44]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [45]:
x2 = torch.randn_like(x)
print(x2)

tensor([[-0.4421, -0.3027, -0.8258,  0.1521, -2.1882],
        [ 2.8988, -0.8185, -1.5123, -0.1102,  0.0811]])


In [46]:
x3 = torch.ones_like(x)
print(x3)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [48]:
torch.manual_seed(72)
x = torch.rand(2, 3)
print(x)

tensor([[0.3250, 0.3631, 0.1917],
        [0.5239, 0.9504, 0.2182]])


In [49]:
torch.manual_seed(72)
x = torch.rand(2, 3)
print(x)

tensor([[0.3250, 0.3631, 0.1917],
        [0.5239, 0.9504, 0.2182]])


In [50]:
x.shape

torch.Size([2, 3])

In [51]:
x.size()  # equivalent to x.shape

torch.Size([2, 3])

In [52]:
x.device

device(type='cpu')

In [53]:
x.layout

torch.strided