# NumPy 

NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks. Plus we will use it to generate data for our analysis examples later on!

In [1]:
import numpy as np

In [2]:
nourdine = [1,2,3]

In [4]:
nourdine

[1, 2, 3]

In [7]:
np.array(nourdine)

array([1, 2, 3])

In [10]:
my_matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [11]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate arrays.

### arange

Return evenly spaced values within a given interval.

In [15]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [19]:
np.arange(0,11,1.5)

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5])

### zeros and ones

Generate arrays of zeros or ones.

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [26]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### linspace 
Return evenly spaced numbers over a specified interval.

In [31]:
np.linspace(0,4,20)

array([0.        , 0.21052632, 0.42105263, 0.63157895, 0.84210526,
       1.05263158, 1.26315789, 1.47368421, 1.68421053, 1.89473684,
       2.10526316, 2.31578947, 2.52631579, 2.73684211, 2.94736842,
       3.15789474, 3.36842105, 3.57894737, 3.78947368, 4.        ])

In [32]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.linspace(0,10,2) * np.eye(2)

array([[ 0.,  0.],
       [ 0., 10.]])

## Random 
Numpy also has lots of ways to create random number arrays:

In [39]:
np.random.rand(4)

array([0.34804167, 0.93229562, 0.29849067, 0.81153544])

In [41]:
np.random.randn(5,4)

array([[-0.73285379, -0.5935904 ,  0.21667229, -0.21941205],
       [ 1.14794015, -0.27715536,  0.38599603, -0.39100212],
       [-0.31070443,  1.39730183,  0.27567369,  2.58149584],
       [-2.21019214, -1.61569926, -0.60436214, -0.65367506],
       [ 0.77286304,  0.73723823, -0.54944553, -0.52516682]])

In [42]:
np.random.seed(555)

In [45]:
np.random.rand(4)

array([0.62043546, 0.45295964, 0.23976742, 0.03450459])

In [47]:
np.random.randint(1,3100)

507

In [52]:
np.random.randint(1,100,50)

array([49, 59, 49, 52, 77, 41, 26, 39, 86,  5, 56, 22, 91, 79, 40, 37, 24,
       95, 36, 52, 18, 47, 14, 31, 50, 17, 63, 97, 73, 66, 66,  4, 23, 60,
       23, 98, 44, 45, 79, 14,  5, 84, 54, 98, 59,  4, 71, 70, 64, 50])

In [60]:
np.random.seed(44)
np.random.rand(4)

array([0.83484215, 0.1047961 , 0.74464048, 0.36050084])

In [62]:
np.random.seed(44)
np.random.rand(4)

array([0.83484215, 0.1047961 , 0.74464048, 0.36050084])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [66]:
array = np.arange(25)
ra = np.random.randint(0,50,10)

In [68]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
ra.dtype

dtype('int64')

In [73]:
array.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [74]:
ra.max()

45

In [76]:
ra

array([38, 45, 36,  1, 14, 39, 36, 29, 21, 19])

In [78]:
ra.argmax()

1

In [79]:
ra.min()

1

In [80]:
ra.max()

45

In [82]:
ra.mean()

27.8

In [84]:
ra.argmin()

3

In [85]:
ra.shape

(10,)

In [86]:
array.shape

(25,)

In [87]:
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
array.shape

(25,)

### dtype

You can also grab the data type of the object in the array: 

In [93]:
arr = np.array(np.random.rand(4,40,50))

In [94]:
arr.shape

(4, 40, 50)

In [95]:
arr.dtype

dtype('float64')

In [96]:
arr

array([[[8.81824281e-01, 6.46410562e-01, 2.13824812e-01, ...,
         9.52846616e-02, 7.97977485e-01, 2.68656370e-01],
        [9.11414913e-01, 9.01743980e-01, 1.58578004e-02, ...,
         5.09806721e-01, 8.57426070e-01, 3.63775170e-04],
        [7.79144999e-01, 7.92295178e-01, 6.41396476e-02, ...,
         5.52061067e-01, 4.87120304e-01, 5.49421333e-01],
        ...,
        [8.60832442e-01, 7.04445463e-01, 2.32379766e-01, ...,
         5.18920440e-01, 3.69212181e-01, 7.53809444e-01],
        [1.63117749e-01, 7.71133468e-01, 9.25317254e-01, ...,
         1.28834629e-02, 1.11648826e-01, 5.11913512e-01],
        [1.84558664e-01, 7.12159904e-01, 9.10796636e-01, ...,
         1.59216861e-02, 5.12464628e-02, 5.14623301e-01]],

       [[1.39813091e-01, 7.29286957e-01, 2.96969046e-02, ...,
         4.36752310e-01, 2.83374755e-01, 1.41723548e-01],
        [8.99974003e-01, 4.51182215e-01, 5.28951578e-01, ...,
         8.84045475e-01, 7.86730460e-01, 7.17106977e-01],
        [5.85301219e-01, 