# NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
array = np.arange(0,11)

In [3]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array[3]

3

In [6]:
array[3:8]

array([3, 4, 5, 6, 7])

In [8]:
array[0:4] = 100

In [9]:
array

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [10]:
slice = array[1:5]

In [11]:
slice

array([100, 100, 100,   4])

In [12]:
slice[:]=44

In [13]:
slice

array([44, 44, 44, 44])

In [14]:
array

array([100,  44,  44,  44,  44,   5,   6,   7,   8,   9,  10])

In [15]:
arr_copy = array.copy()

In [17]:
arr_copy

array([100,  44,  44,  44,  44,   5,   6,   7,   8,   9,  10])

In [18]:
arr_copy[1:3]=25

In [19]:
arr_copy

array([100,  25,  25,  44,  44,   5,   6,   7,   8,   9,  10])

In [20]:
array

array([100,  44,  44,  44,  44,   5,   6,   7,   8,   9,  10])

In [21]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))


In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[0]

array([ 5, 10, 15])

In [27]:
arr_2d[0][1]

10

In [28]:
arr_2d[0,1]

10

In [29]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [30]:
arr_2d[2]

array([35, 40, 45])

In [31]:
arr_2d[2,:]

array([35, 40, 45])

In [32]:
arr_2d < 30

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

# NumPy Operations

In [33]:
arr = np.arange(0,10)

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [37]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
arr / arr

/home/nourpc/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [39]:
1/arr

/home/nourpc/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [40]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

In [41]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [42]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
np.sqrt(arr**2)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [46]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [47]:
np.log(arr)

/home/nourpc/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Summary Statistics on Arrays


In [50]:
arr = np.arange(0,10)

In [51]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr.sum()

45

In [53]:
arr.mean()

4.5

In [54]:
arr.max()

9

In [55]:
arr.var()

8.25

In [56]:
arr.std()

2.8722813232690143

In [57]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [58]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
arr_2d.sum()

78

In [61]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

By passing in <tt>axis=0</tt>, we're returning an array of sums along the vertical axis, essentially <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

In [64]:
 arr_2d.shape

(3, 4)

In [65]:
arr_2d.sum(axis=1)

array([10, 26, 42])